# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WoowaHanzo_iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod ‘Firebase/Core’
pod ‘Firebase/Database’
pod ‘Firebase/Auth’
pod 'Firebase/Storage'

pod 'ImageViewer'
pod 'Kingfisher', '~> 3.0'
pod 'NVActivityIndicatorView'
pod "BSImagePicker", "~> 2.4"

  # Pods for WoowaHanzo_iOS

  target 'WoowaHanzo_iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WoowaHanzo_iOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
